# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

import unittest

import seel_python_sdk
from seel_python_sdk.model.product_update_product_details_request_product_attributes import ProductUpdateProductDetailsRequestProductAttributes
from seel_python_sdk import configuration


class TestProductUpdateProductDetailsRequestProductAttributes(unittest.TestCase):
    """ProductUpdateProductDetailsRequestProductAttributes unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
