# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

import unittest

import seel_python_sdk
from seel_python_sdk.model.merchant_list_all_merchants_response import MerchantListAllMerchantsResponse
from seel_python_sdk import configuration


class TestMerchantListAllMerchantsResponse(unittest.TestCase):
    """MerchantListAllMerchantsResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
