# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

import unittest

import seel_python_sdk
from seel_python_sdk.model.product_enabled_services_item import ProductEnabledServicesItem
from seel_python_sdk import configuration


class TestProductEnabledServicesItem(unittest.TestCase):
    """ProductEnabledServicesItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
