# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

import unittest

import seel_python_sdk
from seel_python_sdk.model.claim_claim_details import ClaimClaimDetails
from seel_python_sdk import configuration


class TestClaimClaimDetails(unittest.TestCase):
    """ClaimClaimDetails unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
