# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from seel_python_sdk.paths.partner_claims.get import GetAllClaims
from seel_python_sdk.paths.partner_claims_claim_id.get import GetById
from seel_python_sdk.apis.tags.claim_api_raw import ClaimApiRaw


class ClaimApi(
    GetAllClaims,
    GetById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ClaimApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ClaimApiRaw(api_client)
