# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from seel_python_sdk.paths.partner_orders_order_id_fulfillments_fulfillment_id_cancel.post import CancelFulfillmentRaw
from seel_python_sdk.paths.partner_orders_order_id_fulfillments.post import CreateNewFulfillmentRaw
from seel_python_sdk.paths.partner_orders_order_id_fulfillments_fulfillment_id.get import GetDetailsRaw
from seel_python_sdk.paths.partner_orders_order_id_fulfillments.get import ListFulfillmentsRaw
from seel_python_sdk.paths.partner_orders_order_id_fulfillments_fulfillment_id.post import UpdateFulfillmentDetailsRaw


class FulfillmentApiRaw(
    CancelFulfillmentRaw,
    CreateNewFulfillmentRaw,
    GetDetailsRaw,
    ListFulfillmentsRaw,
    UpdateFulfillmentDetailsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
