# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from seel_python_sdk.paths.partner_invoices_invoice_id.get import GetInvoiceByIdRaw
from seel_python_sdk.paths.partner_invoices.get import ListInvoicesRaw


class InvoiceApiRaw(
    GetInvoiceByIdRaw,
    ListInvoicesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
