# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from seel_python_sdk.paths.partner_merchants.post import CreateNewMerchant
from seel_python_sdk.paths.partner_merchants_merchant_id.get import GetMerchantDetails
from seel_python_sdk.paths.partner_merchants.get import ListAllMerchants
from seel_python_sdk.paths.partner_merchants_merchant_id.post import UpdateMerchantDetails
from seel_python_sdk.apis.tags.merchant_api_raw import MerchantApiRaw


class MerchantApi(
    CreateNewMerchant,
    GetMerchantDetails,
    ListAllMerchants,
    UpdateMerchantDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: MerchantApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = MerchantApiRaw(api_client)
