# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from seel_python_sdk.paths.partner_merchants.post import CreateNewMerchantRaw
from seel_python_sdk.paths.partner_merchants_merchant_id.get import GetMerchantDetailsRaw
from seel_python_sdk.paths.partner_merchants.get import ListAllMerchantsRaw
from seel_python_sdk.paths.partner_merchants_merchant_id.post import UpdateMerchantDetailsRaw


class MerchantApiRaw(
    CreateNewMerchantRaw,
    GetMerchantDetailsRaw,
    ListAllMerchantsRaw,
    UpdateMerchantDetailsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
