# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from seel_python_sdk.paths.partner_orders_batch.post import BatchCreateOrders
from seel_python_sdk.paths.partner_orders_order_id_cancel.post import CancelOrderById
from seel_python_sdk.paths.partner_orders.post import CreateNewOrder
from seel_python_sdk.paths.partner_orders_order_id.get import GetById
from seel_python_sdk.paths.partner_orders_order_id.post import UpdateOrderDetails
from seel_python_sdk.apis.tags.order_api_raw import OrderApiRaw


class OrderApi(
    BatchCreateOrders,
    CancelOrderById,
    CreateNewOrder,
    GetById,
    UpdateOrderDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: OrderApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = OrderApiRaw(api_client)
