# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from seel_python_sdk.paths.partner_products.post import AddNewProduct
from seel_python_sdk.paths.partner_products_batch.post import BatchCreateProducts
from seel_python_sdk.paths.partner_products_product_id.get import GetProductById
from seel_python_sdk.paths.partner_products_product_id_plans.get import ListPlans
from seel_python_sdk.paths.partner_products_product_id.delete import RemoveProductById
from seel_python_sdk.paths.partner_products_product_id.post import UpdateProductDetails
from seel_python_sdk.apis.tags.product_api_raw import ProductApiRaw


class ProductApi(
    AddNewProduct,
    BatchCreateProducts,
    GetProductById,
    ListPlans,
    RemoveProductById,
    UpdateProductDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ProductApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ProductApiRaw(api_client)
