# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from seel_python_sdk.paths.partner_products.post import AddNewProductRaw
from seel_python_sdk.paths.partner_products_batch.post import BatchCreateProductsRaw
from seel_python_sdk.paths.partner_products_product_id.get import GetProductByIdRaw
from seel_python_sdk.paths.partner_products_product_id_plans.get import ListPlansRaw
from seel_python_sdk.paths.partner_products_product_id.delete import RemoveProductByIdRaw
from seel_python_sdk.paths.partner_products_product_id.post import UpdateProductDetailsRaw


class ProductApiRaw(
    AddNewProductRaw,
    BatchCreateProductsRaw,
    GetProductByIdRaw,
    ListPlansRaw,
    RemoveProductByIdRaw,
    UpdateProductDetailsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
