# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from seel_python_sdk.paths.partner_quotes.post import GenerateQuoteRaw
from seel_python_sdk.paths.partner_quotes_quote_id.get import GetByIdRaw


class QuoteApiRaw(
    GenerateQuoteRaw,
    GetByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
