# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import seel_python_sdk
from seel_python_sdk.paths.partner_products_product_id import delete
from seel_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestPartnerProductsProductId(ApiTestMixin, unittest.TestCase):
    """
    PartnerProductsProductId unit test stubs
        Delete a product
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
