# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import seel_python_sdk
from seel_python_sdk.paths.partner_invoices import get
from seel_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestPartnerInvoices(ApiTestMixin, unittest.TestCase):
    """
    PartnerInvoices unit test stubs
        List invoices
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
