# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from seel_python_sdk import schemas  # noqa: F401


class ClaimClaimDetailsItemClaimItems(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    Items related to the claim
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['ClaimClaimDetailsItemClaimItemsItem']:
            return ClaimClaimDetailsItemClaimItemsItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['ClaimClaimDetailsItemClaimItemsItem'], typing.List['ClaimClaimDetailsItemClaimItemsItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'ClaimClaimDetailsItemClaimItems':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'ClaimClaimDetailsItemClaimItemsItem':
        return super().__getitem__(i)

from seel_python_sdk.model.claim_claim_details_item_claim_items_item import ClaimClaimDetailsItemClaimItemsItem
