# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from seel_python_sdk import schemas  # noqa: F401


class FulfillmentUpdateFulfillmentDetailsRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "updated_ts",
            "carrier",
            "tracking_number",
            "line_items",
            "shipment_status",
        }
        
        class properties:
            updated_ts = schemas.DateTimeSchema
            tracking_number = schemas.StrSchema
            carrier = schemas.StrSchema
            
            
            class shipment_status(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "shipped": "SHIPPED",
                        "delivered": "DELIVERED",
                    }
                
                @schemas.classproperty
                def SHIPPED(cls):
                    return cls("shipped")
                
                @schemas.classproperty
                def DELIVERED(cls):
                    return cls("delivered")
        
            @staticmethod
            def line_items() -> typing.Type['FulfillmentUpdateFulfillmentDetailsRequestLineItems']:
                return FulfillmentUpdateFulfillmentDetailsRequestLineItems
            tracking_url = schemas.StrSchema
            __annotations__ = {
                "updated_ts": updated_ts,
                "tracking_number": tracking_number,
                "carrier": carrier,
                "shipment_status": shipment_status,
                "line_items": line_items,
                "tracking_url": tracking_url,
            }
    
    updated_ts: MetaOapg.properties.updated_ts
    carrier: MetaOapg.properties.carrier
    tracking_number: MetaOapg.properties.tracking_number
    line_items: 'FulfillmentUpdateFulfillmentDetailsRequestLineItems'
    shipment_status: MetaOapg.properties.shipment_status
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updated_ts"]) -> MetaOapg.properties.updated_ts: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tracking_number"]) -> MetaOapg.properties.tracking_number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["carrier"]) -> MetaOapg.properties.carrier: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shipment_status"]) -> MetaOapg.properties.shipment_status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["line_items"]) -> 'FulfillmentUpdateFulfillmentDetailsRequestLineItems': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tracking_url"]) -> MetaOapg.properties.tracking_url: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["updated_ts", "tracking_number", "carrier", "shipment_status", "line_items", "tracking_url", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updated_ts"]) -> MetaOapg.properties.updated_ts: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tracking_number"]) -> MetaOapg.properties.tracking_number: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["carrier"]) -> MetaOapg.properties.carrier: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shipment_status"]) -> MetaOapg.properties.shipment_status: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["line_items"]) -> 'FulfillmentUpdateFulfillmentDetailsRequestLineItems': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tracking_url"]) -> typing.Union[MetaOapg.properties.tracking_url, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["updated_ts", "tracking_number", "carrier", "shipment_status", "line_items", "tracking_url", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        updated_ts: typing.Union[MetaOapg.properties.updated_ts, str, datetime, ],
        carrier: typing.Union[MetaOapg.properties.carrier, str, ],
        tracking_number: typing.Union[MetaOapg.properties.tracking_number, str, ],
        line_items: 'FulfillmentUpdateFulfillmentDetailsRequestLineItems',
        shipment_status: typing.Union[MetaOapg.properties.shipment_status, str, ],
        tracking_url: typing.Union[MetaOapg.properties.tracking_url, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FulfillmentUpdateFulfillmentDetailsRequest':
        return super().__new__(
            cls,
            *args,
            updated_ts=updated_ts,
            carrier=carrier,
            tracking_number=tracking_number,
            line_items=line_items,
            shipment_status=shipment_status,
            tracking_url=tracking_url,
            _configuration=_configuration,
            **kwargs,
        )

from seel_python_sdk.model.fulfillment_update_fulfillment_details_request_line_items import FulfillmentUpdateFulfillmentDetailsRequestLineItems
