# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from seel_python_sdk import schemas  # noqa: F401


class MerchantCreateNewMerchantRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "shop_id",
            "contact_name",
            "admin_domain",
            "seel_services",
            "shop_domain",
            "shop_platform",
            "shop_currency",
            "shop_name",
            "contact_email",
        }
        
        class properties:
            shop_id = schemas.StrSchema
            admin_domain = schemas.StrSchema
            shop_domain = schemas.StrSchema
            shop_platform = schemas.StrSchema
            shop_currency = schemas.StrSchema
            shop_name = schemas.StrSchema
            contact_name = schemas.StrSchema
            contact_email = schemas.StrSchema
        
            @staticmethod
            def seel_services() -> typing.Type['MerchantCreateNewMerchantRequestSeelServices']:
                return MerchantCreateNewMerchantRequestSeelServices
            contact_phone_number = schemas.StrSchema
            __annotations__ = {
                "shop_id": shop_id,
                "admin_domain": admin_domain,
                "shop_domain": shop_domain,
                "shop_platform": shop_platform,
                "shop_currency": shop_currency,
                "shop_name": shop_name,
                "contact_name": contact_name,
                "contact_email": contact_email,
                "seel_services": seel_services,
                "contact_phone_number": contact_phone_number,
            }
    
    shop_id: MetaOapg.properties.shop_id
    contact_name: MetaOapg.properties.contact_name
    admin_domain: MetaOapg.properties.admin_domain
    seel_services: 'MerchantCreateNewMerchantRequestSeelServices'
    shop_domain: MetaOapg.properties.shop_domain
    shop_platform: MetaOapg.properties.shop_platform
    shop_currency: MetaOapg.properties.shop_currency
    shop_name: MetaOapg.properties.shop_name
    contact_email: MetaOapg.properties.contact_email
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shop_id"]) -> MetaOapg.properties.shop_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["admin_domain"]) -> MetaOapg.properties.admin_domain: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shop_domain"]) -> MetaOapg.properties.shop_domain: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shop_platform"]) -> MetaOapg.properties.shop_platform: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shop_currency"]) -> MetaOapg.properties.shop_currency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shop_name"]) -> MetaOapg.properties.shop_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contact_name"]) -> MetaOapg.properties.contact_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contact_email"]) -> MetaOapg.properties.contact_email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["seel_services"]) -> 'MerchantCreateNewMerchantRequestSeelServices': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contact_phone_number"]) -> MetaOapg.properties.contact_phone_number: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["shop_id", "admin_domain", "shop_domain", "shop_platform", "shop_currency", "shop_name", "contact_name", "contact_email", "seel_services", "contact_phone_number", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shop_id"]) -> MetaOapg.properties.shop_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["admin_domain"]) -> MetaOapg.properties.admin_domain: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shop_domain"]) -> MetaOapg.properties.shop_domain: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shop_platform"]) -> MetaOapg.properties.shop_platform: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shop_currency"]) -> MetaOapg.properties.shop_currency: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shop_name"]) -> MetaOapg.properties.shop_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contact_name"]) -> MetaOapg.properties.contact_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contact_email"]) -> MetaOapg.properties.contact_email: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["seel_services"]) -> 'MerchantCreateNewMerchantRequestSeelServices': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contact_phone_number"]) -> typing.Union[MetaOapg.properties.contact_phone_number, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["shop_id", "admin_domain", "shop_domain", "shop_platform", "shop_currency", "shop_name", "contact_name", "contact_email", "seel_services", "contact_phone_number", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        shop_id: typing.Union[MetaOapg.properties.shop_id, str, ],
        contact_name: typing.Union[MetaOapg.properties.contact_name, str, ],
        admin_domain: typing.Union[MetaOapg.properties.admin_domain, str, ],
        seel_services: 'MerchantCreateNewMerchantRequestSeelServices',
        shop_domain: typing.Union[MetaOapg.properties.shop_domain, str, ],
        shop_platform: typing.Union[MetaOapg.properties.shop_platform, str, ],
        shop_currency: typing.Union[MetaOapg.properties.shop_currency, str, ],
        shop_name: typing.Union[MetaOapg.properties.shop_name, str, ],
        contact_email: typing.Union[MetaOapg.properties.contact_email, str, ],
        contact_phone_number: typing.Union[MetaOapg.properties.contact_phone_number, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MerchantCreateNewMerchantRequest':
        return super().__new__(
            cls,
            *args,
            shop_id=shop_id,
            contact_name=contact_name,
            admin_domain=admin_domain,
            seel_services=seel_services,
            shop_domain=shop_domain,
            shop_platform=shop_platform,
            shop_currency=shop_currency,
            shop_name=shop_name,
            contact_email=contact_email,
            contact_phone_number=contact_phone_number,
            _configuration=_configuration,
            **kwargs,
        )

from seel_python_sdk.model.merchant_create_new_merchant_request_seel_services import MerchantCreateNewMerchantRequestSeelServices
