# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from seel_python_sdk import schemas  # noqa: F401


class Order(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            order_id = schemas.StrSchema
            order_number = schemas.StrSchema
            cart_id = schemas.StrSchema
            merchant_id = schemas.StrSchema
            session_id = schemas.StrSchema
            device_id = schemas.StrSchema
            client_ip = schemas.StrSchema
            created_ts = schemas.DateTimeSchema
            cancelled_ts = schemas.DateTimeSchema
            updated_ts = schemas.DateTimeSchema
            
            
            class line_items(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Item']:
                        return Item
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['Item'], typing.List['Item']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'line_items':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Item':
                    return super().__getitem__(i)
        
            @staticmethod
            def shipping_address() -> typing.Type['Address']:
                return Address
            
            
            class fulfillments(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Fulfillment']:
                        return Fulfillment
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['Fulfillment'], typing.List['Fulfillment']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'fulfillments':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Fulfillment':
                    return super().__getitem__(i)
            
            
            class seel_services(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['SeelService']:
                        return SeelService
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['SeelService'], typing.List['SeelService']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'seel_services':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'SeelService':
                    return super().__getitem__(i)
            
            
            class refunds(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['OrderRefund']:
                        return OrderRefund
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['OrderRefund'], typing.List['OrderRefund']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'refunds':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'OrderRefund':
                    return super().__getitem__(i)
        
            @staticmethod
            def customer() -> typing.Type['Customer']:
                return Customer
            extra_info = schemas.DictSchema
            __annotations__ = {
                "order_id": order_id,
                "order_number": order_number,
                "cart_id": cart_id,
                "merchant_id": merchant_id,
                "session_id": session_id,
                "device_id": device_id,
                "client_ip": client_ip,
                "created_ts": created_ts,
                "cancelled_ts": cancelled_ts,
                "updated_ts": updated_ts,
                "line_items": line_items,
                "shipping_address": shipping_address,
                "fulfillments": fulfillments,
                "seel_services": seel_services,
                "refunds": refunds,
                "customer": customer,
                "extra_info": extra_info,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["order_id"]) -> MetaOapg.properties.order_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["order_number"]) -> MetaOapg.properties.order_number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cart_id"]) -> MetaOapg.properties.cart_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merchant_id"]) -> MetaOapg.properties.merchant_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["session_id"]) -> MetaOapg.properties.session_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["device_id"]) -> MetaOapg.properties.device_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["client_ip"]) -> MetaOapg.properties.client_ip: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created_ts"]) -> MetaOapg.properties.created_ts: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cancelled_ts"]) -> MetaOapg.properties.cancelled_ts: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updated_ts"]) -> MetaOapg.properties.updated_ts: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["line_items"]) -> MetaOapg.properties.line_items: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shipping_address"]) -> 'Address': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fulfillments"]) -> MetaOapg.properties.fulfillments: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["seel_services"]) -> MetaOapg.properties.seel_services: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["refunds"]) -> MetaOapg.properties.refunds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customer"]) -> 'Customer': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["extra_info"]) -> MetaOapg.properties.extra_info: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["order_id", "order_number", "cart_id", "merchant_id", "session_id", "device_id", "client_ip", "created_ts", "cancelled_ts", "updated_ts", "line_items", "shipping_address", "fulfillments", "seel_services", "refunds", "customer", "extra_info", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["order_id"]) -> typing.Union[MetaOapg.properties.order_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["order_number"]) -> typing.Union[MetaOapg.properties.order_number, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cart_id"]) -> typing.Union[MetaOapg.properties.cart_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merchant_id"]) -> typing.Union[MetaOapg.properties.merchant_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["session_id"]) -> typing.Union[MetaOapg.properties.session_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["device_id"]) -> typing.Union[MetaOapg.properties.device_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["client_ip"]) -> typing.Union[MetaOapg.properties.client_ip, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created_ts"]) -> typing.Union[MetaOapg.properties.created_ts, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cancelled_ts"]) -> typing.Union[MetaOapg.properties.cancelled_ts, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updated_ts"]) -> typing.Union[MetaOapg.properties.updated_ts, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["line_items"]) -> typing.Union[MetaOapg.properties.line_items, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shipping_address"]) -> typing.Union['Address', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fulfillments"]) -> typing.Union[MetaOapg.properties.fulfillments, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["seel_services"]) -> typing.Union[MetaOapg.properties.seel_services, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["refunds"]) -> typing.Union[MetaOapg.properties.refunds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customer"]) -> typing.Union['Customer', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["extra_info"]) -> typing.Union[MetaOapg.properties.extra_info, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["order_id", "order_number", "cart_id", "merchant_id", "session_id", "device_id", "client_ip", "created_ts", "cancelled_ts", "updated_ts", "line_items", "shipping_address", "fulfillments", "seel_services", "refunds", "customer", "extra_info", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        order_id: typing.Union[MetaOapg.properties.order_id, str, schemas.Unset] = schemas.unset,
        order_number: typing.Union[MetaOapg.properties.order_number, str, schemas.Unset] = schemas.unset,
        cart_id: typing.Union[MetaOapg.properties.cart_id, str, schemas.Unset] = schemas.unset,
        merchant_id: typing.Union[MetaOapg.properties.merchant_id, str, schemas.Unset] = schemas.unset,
        session_id: typing.Union[MetaOapg.properties.session_id, str, schemas.Unset] = schemas.unset,
        device_id: typing.Union[MetaOapg.properties.device_id, str, schemas.Unset] = schemas.unset,
        client_ip: typing.Union[MetaOapg.properties.client_ip, str, schemas.Unset] = schemas.unset,
        created_ts: typing.Union[MetaOapg.properties.created_ts, str, datetime, schemas.Unset] = schemas.unset,
        cancelled_ts: typing.Union[MetaOapg.properties.cancelled_ts, str, datetime, schemas.Unset] = schemas.unset,
        updated_ts: typing.Union[MetaOapg.properties.updated_ts, str, datetime, schemas.Unset] = schemas.unset,
        line_items: typing.Union[MetaOapg.properties.line_items, list, tuple, schemas.Unset] = schemas.unset,
        shipping_address: typing.Union['Address', schemas.Unset] = schemas.unset,
        fulfillments: typing.Union[MetaOapg.properties.fulfillments, list, tuple, schemas.Unset] = schemas.unset,
        seel_services: typing.Union[MetaOapg.properties.seel_services, list, tuple, schemas.Unset] = schemas.unset,
        refunds: typing.Union[MetaOapg.properties.refunds, list, tuple, schemas.Unset] = schemas.unset,
        customer: typing.Union['Customer', schemas.Unset] = schemas.unset,
        extra_info: typing.Union[MetaOapg.properties.extra_info, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Order':
        return super().__new__(
            cls,
            *args,
            order_id=order_id,
            order_number=order_number,
            cart_id=cart_id,
            merchant_id=merchant_id,
            session_id=session_id,
            device_id=device_id,
            client_ip=client_ip,
            created_ts=created_ts,
            cancelled_ts=cancelled_ts,
            updated_ts=updated_ts,
            line_items=line_items,
            shipping_address=shipping_address,
            fulfillments=fulfillments,
            seel_services=seel_services,
            refunds=refunds,
            customer=customer,
            extra_info=extra_info,
            _configuration=_configuration,
            **kwargs,
        )

from seel_python_sdk.model.address import Address
from seel_python_sdk.model.customer import Customer
from seel_python_sdk.model.fulfillment import Fulfillment
from seel_python_sdk.model.item import Item
from seel_python_sdk.model.order_refund import OrderRefund
from seel_python_sdk.model.seel_service import SeelService
