# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from seel_python_sdk import schemas  # noqa: F401


class OrderCreateNewOrderRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "created_ts",
            "order_number",
            "session_id",
            "line_items",
            "shipping_address",
            "order_id",
            "customer",
        }
        
        class properties:
            order_id = schemas.StrSchema
            order_number = schemas.StrSchema
            session_id = schemas.StrSchema
            created_ts = schemas.StrSchema
            
            
            class line_items(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Item']:
                        return Item
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['Item'], typing.List['Item']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'line_items':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Item':
                    return super().__getitem__(i)
        
            @staticmethod
            def shipping_address() -> typing.Type['Address']:
                return Address
        
            @staticmethod
            def customer() -> typing.Type['Customer']:
                return Customer
            cart_id = schemas.StrSchema
            merchant_id = schemas.StrSchema
            device_id = schemas.StrSchema
            client_ip = schemas.StrSchema
        
            @staticmethod
            def seel_services() -> typing.Type['OrderCreateNewOrderRequestSeelServices']:
                return OrderCreateNewOrderRequestSeelServices
            extra_info = schemas.DictSchema
            __annotations__ = {
                "order_id": order_id,
                "order_number": order_number,
                "session_id": session_id,
                "created_ts": created_ts,
                "line_items": line_items,
                "shipping_address": shipping_address,
                "customer": customer,
                "cart_id": cart_id,
                "merchant_id": merchant_id,
                "device_id": device_id,
                "client_ip": client_ip,
                "seel_services": seel_services,
                "extra_info": extra_info,
            }
    
    created_ts: MetaOapg.properties.created_ts
    order_number: MetaOapg.properties.order_number
    session_id: MetaOapg.properties.session_id
    line_items: MetaOapg.properties.line_items
    shipping_address: 'Address'
    order_id: MetaOapg.properties.order_id
    customer: 'Customer'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["order_id"]) -> MetaOapg.properties.order_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["order_number"]) -> MetaOapg.properties.order_number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["session_id"]) -> MetaOapg.properties.session_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created_ts"]) -> MetaOapg.properties.created_ts: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["line_items"]) -> MetaOapg.properties.line_items: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shipping_address"]) -> 'Address': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customer"]) -> 'Customer': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cart_id"]) -> MetaOapg.properties.cart_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merchant_id"]) -> MetaOapg.properties.merchant_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["device_id"]) -> MetaOapg.properties.device_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["client_ip"]) -> MetaOapg.properties.client_ip: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["seel_services"]) -> 'OrderCreateNewOrderRequestSeelServices': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["extra_info"]) -> MetaOapg.properties.extra_info: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["order_id", "order_number", "session_id", "created_ts", "line_items", "shipping_address", "customer", "cart_id", "merchant_id", "device_id", "client_ip", "seel_services", "extra_info", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["order_id"]) -> MetaOapg.properties.order_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["order_number"]) -> MetaOapg.properties.order_number: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["session_id"]) -> MetaOapg.properties.session_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created_ts"]) -> MetaOapg.properties.created_ts: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["line_items"]) -> MetaOapg.properties.line_items: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shipping_address"]) -> 'Address': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customer"]) -> 'Customer': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cart_id"]) -> typing.Union[MetaOapg.properties.cart_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merchant_id"]) -> typing.Union[MetaOapg.properties.merchant_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["device_id"]) -> typing.Union[MetaOapg.properties.device_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["client_ip"]) -> typing.Union[MetaOapg.properties.client_ip, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["seel_services"]) -> typing.Union['OrderCreateNewOrderRequestSeelServices', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["extra_info"]) -> typing.Union[MetaOapg.properties.extra_info, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["order_id", "order_number", "session_id", "created_ts", "line_items", "shipping_address", "customer", "cart_id", "merchant_id", "device_id", "client_ip", "seel_services", "extra_info", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        created_ts: typing.Union[MetaOapg.properties.created_ts, str, ],
        order_number: typing.Union[MetaOapg.properties.order_number, str, ],
        session_id: typing.Union[MetaOapg.properties.session_id, str, ],
        line_items: typing.Union[MetaOapg.properties.line_items, list, tuple, ],
        shipping_address: 'Address',
        order_id: typing.Union[MetaOapg.properties.order_id, str, ],
        customer: 'Customer',
        cart_id: typing.Union[MetaOapg.properties.cart_id, str, schemas.Unset] = schemas.unset,
        merchant_id: typing.Union[MetaOapg.properties.merchant_id, str, schemas.Unset] = schemas.unset,
        device_id: typing.Union[MetaOapg.properties.device_id, str, schemas.Unset] = schemas.unset,
        client_ip: typing.Union[MetaOapg.properties.client_ip, str, schemas.Unset] = schemas.unset,
        seel_services: typing.Union['OrderCreateNewOrderRequestSeelServices', schemas.Unset] = schemas.unset,
        extra_info: typing.Union[MetaOapg.properties.extra_info, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'OrderCreateNewOrderRequest':
        return super().__new__(
            cls,
            *args,
            created_ts=created_ts,
            order_number=order_number,
            session_id=session_id,
            line_items=line_items,
            shipping_address=shipping_address,
            order_id=order_id,
            customer=customer,
            cart_id=cart_id,
            merchant_id=merchant_id,
            device_id=device_id,
            client_ip=client_ip,
            seel_services=seel_services,
            extra_info=extra_info,
            _configuration=_configuration,
            **kwargs,
        )

from seel_python_sdk.model.address import Address
from seel_python_sdk.model.customer import Customer
from seel_python_sdk.model.item import Item
from seel_python_sdk.model.order_create_new_order_request_seel_services import OrderCreateNewOrderRequestSeelServices
