# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAddress(TypedDict):
    # The first line of the shipping address
    address_1: str

    # The city of the shipping address
    city: str

    # The state or province code of the shipping address
    state: str

    # The zipcode of the shipping address
    zipcode: str

    # ISO 3166-1 alpha-2 country code of the shipping address
    country: str

class OptionalAddress(TypedDict, total=False):
    # The second line of the shipping address
    address_2: str

class Address(RequiredAddress, OptionalAddress):
    pass
