# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from seel_python_sdk.type.claim import Claim

class RequiredClaimGetAllClaimsResponse(TypedDict):
    pass

class OptionalClaimGetAllClaimsResponse(TypedDict, total=False):
    # Current page number.
    page: int

    # Number of claims per page.
    page_size: int

    # Total number of claims.
    total: int

    # List of claims.
    claims: typing.List[Claim]

class ClaimGetAllClaimsResponse(RequiredClaimGetAllClaimsResponse, OptionalClaimGetAllClaimsResponse):
    pass
