# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredClaimClaimDetailsItemClaimItemsItem(TypedDict):
    pass

class OptionalClaimClaimDetailsItemClaimItemsItem(TypedDict, total=False):
    # The line item id covered by the contract.
    line_item_id: str

    # The quantity of the line item covered by the contract.
    quantity: int

    # The reason of the claim.
    reason: str

class ClaimClaimDetailsItemClaimItemsItem(RequiredClaimClaimDetailsItemClaimItemsItem, OptionalClaimClaimDetailsItemClaimItemsItem):
    pass
