# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from seel_python_sdk.type.claim_claim_details import ClaimClaimDetails

class RequiredClaim(TypedDict):
    pass

class OptionalClaim(TypedDict, total=False):
    # The unique identifier of the claim.
    claim_id: str

    # The identifier of the order associated with the claim.
    order_id: str

    # The identifier of the contract associated with the claim.
    contract_id: str

    # The settled amount of the claim.
    payout_amount: typing.Union[int, float]

    # The status of the claim.
    status: str

    # The status of the claim.
    claim_type: str

    # The reject reason of the claim.
    reject_reason: str

    claim_details: ClaimClaimDetails

    # The timestamp in milliseconds when the contract was cancelled (if applicable).
    updated_ts: typing.Optional[datetime]

    # The timestamp in milliseconds when the contract was created.
    created_ts: typing.Optional[datetime]

class Claim(RequiredClaim, OptionalClaim):
    pass
