# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from seel_python_sdk.type.contract_covered_items import ContractCoveredItems
from seel_python_sdk.type.customer import Customer

class RequiredContract(TypedDict):
    pass

class OptionalContract(TypedDict, total=False):
    # The unique identifier of the contract.
    contract_id: str

    # The identifier of the order associated with the contract.
    order_id: str

    # The identifier of the quote associated with the contract.
    quote_id: str

    customer: Customer

    # The premium (i.e., cost) of the contract.
    premium: typing.Union[int, float]

    # The tax applied to the contract premium.
    premium_tax: typing.Union[int, float]

    # The currency of the contract.
    currency: str

    # The current status of the contract (e.g., \"active\", \"cancelled\").
    status: str

    # The timestamp in millisecond when the contract was cancelled (if applicable).
    cancelled_ts: typing.Optional[datetime]

    # The timestamp in millisecond when the contract was created.
    created_ts: typing.Optional[datetime]

    # The timestamp in millisecond when the contract was updated.
    updated_ts: typing.Optional[datetime]

    covered_items: ContractCoveredItems

class Contract(RequiredContract, OptionalContract):
    pass
