# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredContractCoveredItemsItem(TypedDict):
    pass

class OptionalContractCoveredItemsItem(TypedDict, total=False):
    # The line item id covered by the contract.
    line_item_id: str

    # The quantity of the line item covered by the contract.
    quantity: int

    # The ID of the product.
    product_id: str

    # The ID of the product variant.
    variant_id: str

    # The tracking number associated with the asset shipment.
    tracking_number: str

    # The carrier used to ship the asset.
    carrier: str

    # The value covered by the contract.
    covered_value: typing.Union[int, float]

class ContractCoveredItemsItem(RequiredContractCoveredItemsItem, OptionalContractCoveredItemsItem):
    pass
