# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from seel_python_sdk.type.contract import Contract

class RequiredContractListContractsResponse(TypedDict):
    pass

class OptionalContractListContractsResponse(TypedDict, total=False):
    # Current page number.
    page: int

    # Number of contracts per page.
    page_size: int

    # Total number of contracts.
    total: int

    # List of contracts.
    contracts: typing.List[Contract]

class ContractListContractsResponse(RequiredContractListContractsResponse, OptionalContractListContractsResponse):
    pass
