# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredEvent(TypedDict):
    pass

class OptionalEvent(TypedDict, total=False):
    # Event ID
    event_id: str

    # Session ID
    session_id: str

    # Event created timestamp
    event_ts: str

    # Customer ID
    customer_id: str

    # Device ID
    device_id: str

    # Browser IP address
    browser_ip: str

    # Event source
    event_source: str

    # Event type
    event_type: str

    event_info: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

class Event(RequiredEvent, OptionalEvent):
    pass
