# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from seel_python_sdk.type.item import Item

class RequiredEventInfo(TypedDict):
    pass

class OptionalEventInfo(TypedDict, total=False):
    # Cart ID
    cart_id: str

    # The list of items associated with the event.
    items: typing.List[Item]

    # Additional information for the event
    extra_info: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

class EventInfo(RequiredEventInfo, OptionalEventInfo):
    pass
