# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from seel_python_sdk.type.fulfillment_update_fulfillment_details_request_line_items import FulfillmentUpdateFulfillmentDetailsRequestLineItems

class RequiredFulfillmentUpdateFulfillmentDetailsRequest(TypedDict):
    # Fulfillment updated timestamp in milliseconds
    updated_ts: datetime

    # The tracking number of the fulfillment
    tracking_number: str

    # The shipping carrier of the fulfillment
    carrier: str

    # The shipping status of the fulfillment
    shipment_status: str

    line_items: FulfillmentUpdateFulfillmentDetailsRequestLineItems

class OptionalFulfillmentUpdateFulfillmentDetailsRequest(TypedDict, total=False):
    # The tracking url of the fulfillment
    tracking_url: str

class FulfillmentUpdateFulfillmentDetailsRequest(RequiredFulfillmentUpdateFulfillmentDetailsRequest, OptionalFulfillmentUpdateFulfillmentDetailsRequest):
    pass
