# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from seel_python_sdk.type.fulfillment import Fulfillment

class RequiredFulfillmentListFulfillmentsResponse(TypedDict):
    pass

class OptionalFulfillmentListFulfillmentsResponse(TypedDict, total=False):
    # Current page number.
    page: int

    # Number of fulfillments per page.
    page_size: int

    # Total number of fulfillments.
    total: int

    # List of fulfillments.
    fulfillments: typing.List[Fulfillment]

class FulfillmentListFulfillmentsResponse(RequiredFulfillmentListFulfillmentsResponse, OptionalFulfillmentListFulfillmentsResponse):
    pass
