# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from seel_python_sdk.type.invoice_invoice_items import InvoiceInvoiceItems

class RequiredInvoice(TypedDict):
    pass

class OptionalInvoice(TypedDict, total=False):
    # The ID of the invoice.
    invoice_id: str

    # The ID of the merchant.
    merchant_id: str

    # The number of the billing cycle.
    billing_cycle: int

    # The date when the merchant was charged for contracts sold.
    billing_date: str

    # The start date of the billing cycle.
    billing_start_date: str

    # The end date of the billing cycle.
    billing_end_date: str

    # The three-letter currency code (ISO 4217 format).
    currency: str

    # The status of the invoice.
    status: str

    # The amount of the invoice.
    invoice_amount: typing.Union[int, float]

    # URL of the invoice
    invoice_link: str

    invoice_items: InvoiceInvoiceItems

class Invoice(RequiredInvoice, OptionalInvoice):
    pass
