# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from seel_python_sdk.type.invoice import Invoice

class RequiredInvoiceListInvoicesResponse(TypedDict):
    pass

class OptionalInvoiceListInvoicesResponse(TypedDict, total=False):
    # Current page number.
    page: int

    # Number of invoices per page.
    page_size: int

    # Total number of invoices.
    total: int

    # List of invoices.
    invoices: typing.List[Invoice]

class InvoiceListInvoicesResponse(RequiredInvoiceListInvoicesResponse, OptionalInvoiceListInvoicesResponse):
    pass
