# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from seel_python_sdk.type.merchant import Merchant

class RequiredMerchantListAllMerchantsResponse(TypedDict):
    pass

class OptionalMerchantListAllMerchantsResponse(TypedDict, total=False):
    # Current page number.
    page: int

    # Number of merchants per page.
    page_size: int

    # Total number of merchants.
    total: int

    # List of merchants.
    merchants: typing.List[Merchant]

class MerchantListAllMerchantsResponse(RequiredMerchantListAllMerchantsResponse, OptionalMerchantListAllMerchantsResponse):
    pass
