# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredMerchantUpdateMerchantDetailsRequestSeelServicesItem(TypedDict):
    pass

class OptionalMerchantUpdateMerchantDetailsRequestSeelServicesItem(TypedDict, total=False):
    # The product type for the service, e.g. seel-ra, seel-gsp.
    type: str

    # Boolean indicating if the service is currently enabled ('true') or disabled ('false') for the merchant.
    is_enabled: bool

    # Default opt-in setting for the service widget. 'true' means opted in by default. 'false' means opted out by default.
    is_default_on: str

class MerchantUpdateMerchantDetailsRequestSeelServicesItem(RequiredMerchantUpdateMerchantDetailsRequestSeelServicesItem, OptionalMerchantUpdateMerchantDetailsRequestSeelServicesItem):
    pass
