# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredMerchantSeelServicesItem(TypedDict):
    pass

class OptionalMerchantSeelServicesItem(TypedDict, total=False):
    # The product type for the service, e.g. seel-ra, seel-gsp.
    type: str

    # Boolean indicating if the service is currently enabled ('true') or disabled ('false') for the merchant.
    is_enabled: bool

    # Default opt-in setting for the service widget. 'true' means opted in by default. 'false' means opted out by default.
    is_default_on: str

    # The reason why the service is disabled for this merchant if applicable.
    disabled_reason: str

    # The timestamp when the enabled service status was updated.
    updated_ts: datetime

class MerchantSeelServicesItem(RequiredMerchantSeelServicesItem, OptionalMerchantSeelServicesItem):
    pass
