# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from seel_python_sdk.type.merchant_update_merchant_details_request_seel_services import MerchantUpdateMerchantDetailsRequestSeelServices

class RequiredMerchantUpdateMerchantDetailsRequest(TypedDict):
    pass

class OptionalMerchantUpdateMerchantDetailsRequest(TypedDict, total=False):
    # The identifier for the shop or store within the partner's platform.
    shop_id: str

    # The original subdomain domain for the shop provided by the ecommerce platform, e.g. subdomain.myshopify.com
    admin_domain: str

    # The custom domain name assigned to the shop, e.g. www.myshop.com.
    shop_domain: str

    # The source ecommerce platform for the shop, e.g. Shopify, BigCommerce.
    shop_platform: str

    # 3-letter ISO 4217 currency code for the primary currency used in the shop, e.g. USD, EUR.
    shop_currency: str

    # The registered business name for the shop.
    shop_name: str

    # The registered business name for the merchant.
    contact_name: str

    # The contact email address on file for the merchant.
    contact_email: str

    # The phone number on file for the merchant.
    contact_phone_number: str

    seel_services: MerchantUpdateMerchantDetailsRequestSeelServices

class MerchantUpdateMerchantDetailsRequest(RequiredMerchantUpdateMerchantDetailsRequest, OptionalMerchantUpdateMerchantDetailsRequest):
    pass
