# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from seel_python_sdk.type.address import Address
from seel_python_sdk.type.customer import Customer
from seel_python_sdk.type.item import Item

class RequiredOrderUpdateOrderDetailsRequest(TypedDict):
    # Order updated timestamp in milliseconds
    updated_ts: str

class OptionalOrderUpdateOrderDetailsRequest(TypedDict, total=False):
    # The list of items included in the order.
    line_items: typing.List[Item]

    shipping_address: Address

    customer: Customer

    # Additional information for the order
    extra_info: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

class OrderUpdateOrderDetailsRequest(RequiredOrderUpdateOrderDetailsRequest, OptionalOrderUpdateOrderDetailsRequest):
    pass
