# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredProductAddNewProductRequestIdentifiers(TypedDict):
    pass

class OptionalProductAddNewProductRequestIdentifiers(TypedDict, total=False):
    # Serial number of a specific product unit.
    serial_number: str

    # Global Trade Item Number identifier.
    gtin: str

    # Universal Product Code identifier.
    upc: str

    # International Standard Book Number identifier.
    isbn: str

    # Barcode identifying the product.
    barcode: str

class ProductAddNewProductRequestIdentifiers(RequiredProductAddNewProductRequestIdentifiers, OptionalProductAddNewProductRequestIdentifiers):
    pass
