# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from seel_python_sdk.type.product_add_new_product_request_dimensions import ProductAddNewProductRequestDimensions
from seel_python_sdk.type.product_add_new_product_request_identifiers import ProductAddNewProductRequestIdentifiers
from seel_python_sdk.type.product_add_new_product_request_manufacturer_warranty import ProductAddNewProductRequestManufacturerWarranty
from seel_python_sdk.type.product_add_new_product_request_product_attributes import ProductAddNewProductRequestProductAttributes
from seel_python_sdk.type.product_add_new_product_request_weight import ProductAddNewProductRequestWeight

class RequiredProductAddNewProductRequest(TypedDict):
    # Product id.
    product_id: str

    # Name of the product.
    product_title: str

    # The Product Brand or Vendor.
    brand_name: str

    # List price of the product.
    price: typing.Union[int, float]

    # Currency of the price (e.g. USD, EUR).
    currency: str

class OptionalProductAddNewProductRequest(TypedDict, total=False):
    # The unique identifier for the merchant within Seel's system.
    merchant_id: str

    # Variant id, the unique identifier of a product SKU. Use 'product_id' if the product doesn't have any variants.
    variant_id: str

    # Title of the variant.
    variant_title: str

    # Manufacturer of the item.
    manufacturer: str

    # Main product category.
    category_1: str

    # Secondary product category.
    category_2: str

    # Tertiary product category.
    category_3: str

    # Fourth level product category.
    category_4: str

    # Text description of the product.
    product_description: str

    # URL of the product image.
    image_url: str

    # Whether the product requires shipping.
    requires_shipping: bool

    # Manufacturer model number.
    model_number: str

    # Condition - new, used, refurbished.
    condition: str

    # Stock keeping unit.
    sku: str

    identifiers: ProductAddNewProductRequestIdentifiers

    manufacturer_warranty: ProductAddNewProductRequestManufacturerWarranty

    dimensions: ProductAddNewProductRequestDimensions

    weight: ProductAddNewProductRequestWeight

    product_attributes: ProductAddNewProductRequestProductAttributes

    # Timestamp when the product was created.
    created_ts: datetime

    # Timestamp when the product was updated.
    updated_ts: datetime

class ProductAddNewProductRequest(RequiredProductAddNewProductRequest, OptionalProductAddNewProductRequest):
    pass
