# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from seel_python_sdk.type.address import Address
from seel_python_sdk.type.customer import Customer
from seel_python_sdk.type.item import Item

class RequiredQuoteGenerateQuoteRequest(TypedDict):
    # The ID of the shopping session.
    session_id: str

    # The type of the quote.
    type: str

    # The list of items included in the quote.
    line_items: typing.List[Item]

    shipping_address: Address

    customer: Customer

class OptionalQuoteGenerateQuoteRequest(TypedDict, total=False):
    # The ID of a cart.
    cart_id: str

    # The unique identifier for the merchant within Seel's system.
    merchant_id: str

    # The ID of the client device.
    device_id: str

    # The IP address of the client.
    client_ip: str

    # Additional information for the quote
    extra_info: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

class QuoteGenerateQuoteRequest(RequiredQuoteGenerateQuoteRequest, OptionalQuoteGenerateQuoteRequest):
    pass
