# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from seel_python_sdk.pydantic.claim_claim_details_item_claim_items import ClaimClaimDetailsItemClaimItems

class ClaimClaimDetailsItem(BaseModel):
    claim_items: typing.Optional[ClaimClaimDetailsItemClaimItems] = Field(None, alias='claim_items')

    # This field exists when claim_type is delay, loss or theft.
    fulfillment_id: typing.Optional[str] = Field(None, alias='fulfillment_id')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
