# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from seel_python_sdk.pydantic.claim import Claim

class ClaimGetAllClaimsResponse(BaseModel):
    # Current page number.
    page: typing.Optional[int] = Field(None, alias='page')

    # Number of claims per page.
    page_size: typing.Optional[int] = Field(None, alias='page_size')

    # Total number of claims.
    total: typing.Optional[int] = Field(None, alias='total')

    # List of claims.
    claims: typing.Optional[typing.List[Claim]] = Field(None, alias='claims')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
