# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ContractCoveredItemsItem(BaseModel):
    # The line item id covered by the contract.
    line_item_id: typing.Optional[str] = Field(None, alias='line_item_id')

    # The quantity of the line item covered by the contract.
    quantity: typing.Optional[int] = Field(None, alias='quantity')

    # The ID of the product.
    product_id: typing.Optional[str] = Field(None, alias='product_id')

    # The ID of the product variant.
    variant_id: typing.Optional[str] = Field(None, alias='variant_id')

    # The tracking number associated with the asset shipment.
    tracking_number: typing.Optional[str] = Field(None, alias='tracking_number')

    # The carrier used to ship the asset.
    carrier: typing.Optional[str] = Field(None, alias='carrier')

    # The value covered by the contract.
    covered_value: typing.Optional[typing.Union[int, float]] = Field(None, alias='covered_value')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
