# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from seel_python_sdk.pydantic.fulfillment_line_items import FulfillmentLineItems

class Fulfillment(BaseModel):
    # Fulfillment ID
    fulfillment_id: str = Field(alias='fulfillment_id')

    # Fulfillment created timestamp in milliseconds
    created_ts: datetime = Field(alias='created_ts')

    # Fulfillment updated timestamp in milliseconds
    updated_ts: datetime = Field(alias='updated_ts')

    # The tracking number of the fulfillment
    tracking_number: str = Field(alias='tracking_number')

    # The shipping carrier of the fulfillment
    carrier: str = Field(alias='carrier')

    # The shipping status of the fulfillment
    shipment_status: Literal["shipped", "delivered"] = Field(alias='shipment_status')

    line_items: FulfillmentLineItems = Field(alias='line_items')

    # The tracking url of the fulfillment
    tracking_url: typing.Optional[str] = Field(None, alias='tracking_url')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
