# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from seel_python_sdk.pydantic.fulfillment_update_fulfillment_details_request_line_items_item import FulfillmentUpdateFulfillmentDetailsRequestLineItemsItem

FulfillmentUpdateFulfillmentDetailsRequestLineItems = typing.List[FulfillmentUpdateFulfillmentDetailsRequestLineItemsItem]
