# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from seel_python_sdk.pydantic.invoice_invoice_items import InvoiceInvoiceItems

class Invoice(BaseModel):
    # The ID of the invoice.
    invoice_id: typing.Optional[str] = Field(None, alias='invoice_id')

    # The ID of the merchant.
    merchant_id: typing.Optional[str] = Field(None, alias='merchant_id')

    # The number of the billing cycle.
    billing_cycle: typing.Optional[int] = Field(None, alias='billing_cycle')

    # The date when the merchant was charged for contracts sold.
    billing_date: typing.Optional[str] = Field(None, alias='billing_date')

    # The start date of the billing cycle.
    billing_start_date: typing.Optional[str] = Field(None, alias='billing_start_date')

    # The end date of the billing cycle.
    billing_end_date: typing.Optional[str] = Field(None, alias='billing_end_date')

    # The three-letter currency code (ISO 4217 format).
    currency: typing.Optional[str] = Field(None, alias='currency')

    # The status of the invoice.
    status: typing.Optional[Literal["unpaid", "paid"]] = Field(None, alias='status')

    # The amount of the invoice.
    invoice_amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='invoice_amount')

    # URL of the invoice
    invoice_link: typing.Optional[str] = Field(None, alias='invoice_link')

    invoice_items: typing.Optional[InvoiceInvoiceItems] = Field(None, alias='invoice_items')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
