# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class InvoiceInvoiceItemsItem(BaseModel):
    # The ID of the contract sold during the billing cycle.
    contract_id: typing.Optional[str] = Field(None, alias='contract_id')

    # The ID of the order.
    order_id: typing.Optional[str] = Field(None, alias='order_id')

    # Order number
    order_number: typing.Optional[str] = Field(None, alias='order_number')

    # The protection plan name.
    product_type: typing.Optional[str] = Field(None, alias='product_type')

    # The timestamp when the contract was purchased.
    created_ts: typing.Optional[datetime] = Field(None, alias='created_ts')

    # The timestamp when the contract was cancelled.
    cancelled_ts: typing.Optional[datetime] = Field(None, alias='cancelled_ts')

    # The protection cost of the contract to collect from the merchant.
    amount_collected: typing.Optional[typing.Union[int, float]] = Field(None, alias='amount_collected')

    # The amount refunded due to contract cancellation.
    amount_reconciled: typing.Optional[typing.Union[int, float]] = Field(None, alias='amount_reconciled')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
