# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ItemShippingOrigin(BaseModel):
    # ISO 3166-1 alpha-2 country code of the shipping address
    country: str = Field(alias='country')

    # The first line of the shipping address
    address_1: typing.Optional[str] = Field(None, alias='address_1')

    # The second line of the shipping address
    address_2: typing.Optional[str] = Field(None, alias='address_2')

    # The city of the shipping address
    city: typing.Optional[str] = Field(None, alias='city')

    # The state or province code of the shipping address
    state: typing.Optional[str] = Field(None, alias='state')

    # The zipcode of the shipping address
    zipcode: typing.Optional[str] = Field(None, alias='zipcode')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
