# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from seel_python_sdk.pydantic.merchant_create_new_merchant_request_seel_services import MerchantCreateNewMerchantRequestSeelServices

class MerchantCreateNewMerchantRequest(BaseModel):
    # The identifier for the shop or store within the partner's platform.
    shop_id: str = Field(alias='shop_id')

    # The original subdomain domain for the shop provided by the ecommerce platform, e.g. subdomain.myshopify.com
    admin_domain: str = Field(alias='admin_domain')

    # The custom domain name assigned to the shop, e.g. www.myshop.com.
    shop_domain: str = Field(alias='shop_domain')

    # The source ecommerce platform for the shop, e.g. Shopify, BigCommerce.
    shop_platform: str = Field(alias='shop_platform')

    # 3-letter ISO 4217 currency code for the primary currency used in the shop, e.g. USD, EUR.
    shop_currency: str = Field(alias='shop_currency')

    # The registered business name for the shop.
    shop_name: str = Field(alias='shop_name')

    # The registered business name for the merchant.
    contact_name: str = Field(alias='contact_name')

    # The contact email address on file for the merchant.
    contact_email: str = Field(alias='contact_email')

    seel_services: MerchantCreateNewMerchantRequestSeelServices = Field(alias='seel_services')

    # The phone number on file for the merchant.
    contact_phone_number: typing.Optional[str] = Field(None, alias='contact_phone_number')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
