# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from seel_python_sdk.pydantic.order_refund_line_items import OrderRefundLineItems

class OrderRefund(BaseModel):
    # The unique identifier of the claim.
    refund_id: typing.Optional[str] = Field(None, alias='refund_id')

    # The timestamp in milliseconds when the contract was created.
    created_ts: typing.Optional[typing.Optional[datetime]] = Field(None, alias='created_ts')

    # The refund amount.
    refund_amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='refund_amount')

    # The refund reason.
    refund_reason: typing.Optional[str] = Field(None, alias='refund_reason')

    line_items: typing.Optional[OrderRefundLineItems] = Field(None, alias='line_items')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
