# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ProductUpdateProductDetailsRequestManufacturerWarranty(BaseModel):
    # A URL linking to the full details of the manufacturer's warranty, probably on the manufacturer's website.
    url: typing.Optional[str] = Field(None, alias='url')

    # The length of the manufacturer warranty coverage in months.
    term_length: typing.Optional[typing.Union[int, float]] = Field(None, alias='term_length')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
