# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ProductUpdateProductDetailsRequestProductAttributes(BaseModel):
    # Color of the product.
    color: typing.Optional[str] = Field(None, alias='color')

    # Size of the product.
    size: typing.Optional[str] = Field(None, alias='size')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
