# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ProductDimensions(BaseModel):
    # Length of the product in centimeters.
    length: typing.Optional[typing.Union[int, float]] = Field(None, alias='length')

    # Width of the product in centimeters.
    width: typing.Optional[typing.Union[int, float]] = Field(None, alias='width')

    # Height of the product in centimeters.
    height: typing.Optional[typing.Union[int, float]] = Field(None, alias='height')

    # Unit of measurement (e.g., cm, in, ft, m).
    unit: typing.Optional[str] = Field(None, alias='unit')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
