# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ProductWeight(BaseModel):
    # Weight of the product.
    value: typing.Optional[typing.Union[int, float]] = Field(None, alias='value')

    # Unit of weight (e.g., g, oz, lb, kg).
    unit: typing.Optional[str] = Field(None, alias='unit')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
