# coding: utf-8

"""
    Seel API

    Seel API

    The version of the OpenAPI document: 1.3.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ShippingDetails(BaseModel):
    # The weight of the line item in grams. Used to calculate shipping costs.
    weight_g: typing.Optional[typing.Union[int, float]] = Field(None, alias='weight_g')

    # The length of the line item package in centimeters.
    length_cm: typing.Optional[typing.Union[int, float]] = Field(None, alias='length_cm')

    # The height of the line item package in centimeters.
    height_cm: typing.Optional[typing.Union[int, float]] = Field(None, alias='height_cm')

    # The width of the line item package in centimeters.
    width_cm: typing.Optional[typing.Union[int, float]] = Field(None, alias='width_cm')

    # The calculated shipping cost for delivering this particular line item
    shipping_cost: typing.Optional[typing.Union[int, float]] = Field(None, alias='shipping_cost')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
